
INSERT INTO words (id, english, shona) VALUES 
    (1, 'Morning', 'Mangwanani'),
    (2, 'Afternoon', 'Masikati'),
    (3, 'Today', 'Nhasi'),
    (4, 'Tomorrow', 'Mangwana'),
    (5, 'Good Morning', 'Wamukasei'),
    (6, 'eat', 'kudya'),
    (7, 'go ', 'enda'),
    (8, 'bread', 'chingwa'),
    (9, 'food', 'chikafu'),
    (10, 'hungry', 'nzara'),
    (11, 'I am', 'ndine'),
    (12, 'help', 'batsira'),
    (13, 'walk', 'famba'),
    (14, 'far', 'kure'),
    (15, 'see', 'kuona'),
    (16, 'brother', 'bhudhi'),
    (17, 'sister', 'sisi'),
    (18,'name', 'zita'),
    (19, 'Good Afternoon', 'Waswerasei'),
    (20, 'Evening', 'Manheru'),
    (21, 'home', 'kumba'),
    (22, 'house', 'imba'),
    (23, 'book', 'bhuku'),
    (24, 'read', 'verenga'),
    (25, 'time', 'nguva'),
    (26, 'sleep', 'rara'),
    (27, 'mine', 'wangu'),
    (28, 'musikana', 'girl'),
    (29, 'mukomana', 'boy'),
    (30, 'stand ', 'simuka'),
    (31, 'sit', 'gara'),
    (32, 'where', 'kupi'),
    (33, 'want', 'kuda'),
    (34, 'tired', 'kuneta'),
    (35, 'happy', 'kufara');